version: '3'
services:

  hr:
    build: ./hr
    container_name: hr
    environment:
      - HR_DB_USERNAME=hr
      - HR_DB_PASSWORD=hr
      - POSTGRES_DB=hr_db
    ports:
      - "8082:5000"
    volumes:
      - ./hr:/hr
    networks:
      - iam-network
    depends_on:
      - postgres

  rms:
    build: ./rms
    container_name: rms
    environment:
      - RMS_DB_USERNAME=rms
      - RMS_DB_PASSWORD=rms
      - POSTGRES_DB=rms_db
    ports:
      - "8081:5000"
    volumes:
    - ./rms:/rms
    networks:
      - iam-network
    depends_on:
      - postgres

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    volumes:
    - ./app:/app
    networks:
      - iam-network
    depends_on:
      - keycloak

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - iam-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev --http-port=8080
    networks:
      - iam-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - keycloak
    networks:
      - iam-network

volumes:
  postgres_data:

networks:
  iam-network:
    driver: bridge
